CREATE TABLE technical_processes
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                         VARCHAR(255),
    description                  VARCHAR(255),
    is_archived                  BOOLEAN,
    is_shared                    BOOLEAN,
    department_owner_id          BIGINT,
    employee_owner_id            BIGINT,
    date_of_change               TIMESTAMP WITHOUT TIME ZONE,
    employee_who_last_changed_id BIGINT,
    CONSTRAINT pk_technical_processes PRIMARY KEY (id)
);

ALTER TABLE technical_processes
    ADD CONSTRAINT FK_TECHNICAL_PROCESSES_ON_DEPARTMENTOWNER
        FOREIGN KEY (department_owner_id) REFERENCES departments (id);

ALTER TABLE technical_processes
    ADD CONSTRAINT FK_TECHNICAL_PROCESSES_ON_EMPLOYEEOWNER
        FOREIGN KEY (employee_owner_id) REFERENCES employees (id);

ALTER TABLE technical_processes
    ADD CONSTRAINT FK_TECHNICAL_PROCESSES_ON_EMPLOYEEWHOLASTCHANGED
        FOREIGN KEY (employee_who_last_changed_id) REFERENCES employees (id);

INSERT INTO technical_processes(id, name, description, is_archived, is_shared, department_owner_id,
                                employee_owner_id, date_of_change, employee_who_last_changed_id)
VALUES (1, 'Основной тех.процесс', 'Тестовое описание основного ТП', false, true, 1, 1, '2021-10-11 08:00:00.000000', 1),
       (2, 'Доп. тех.процесс', 'Тестовое описание доп. ТП', false, true, 2, 2, '2021-10-11 08:00:00.000000', 2);
