ALTER TABLE units ADD COLUMN IF NOT EXISTS is_recyclebin boolean default false;
ALTER TABLE units ADD COLUMN IF NOT EXISTS unit_type varchar(255);
UPDATE units SET unit_type = 'Системный' WHERE id<60;
ALTER TABLE units ADD COLUMN IF NOT EXISTS general_access boolean;
UPDATE units SET general_access = false WHERE id<60;
ALTER TABLE units ADD COLUMN IF NOT EXISTS department_owner varchar(255);
UPDATE units SET department_owner = '' WHERE id<60;
ALTER TABLE units ADD COLUMN IF NOT EXISTS employee_owner varchar(255);
UPDATE units SET employee_owner = '' WHERE id<60;
ALTER TABLE units ADD COLUMN IF NOT EXISTS date_of_change timestamp without time zone;
UPDATE units SET date_of_change = '2022-03-30 18:36:00' WHERE id<60;
ALTER TABLE units ADD COLUMN IF NOT EXISTS employee_change varchar(255);
UPDATE units SET employee_change = '' WHERE id<60;
UPDATE units SET sort_number = '003' WHERE id = 1;
UPDATE units SET sort_number = '004' WHERE id = 2;
UPDATE units SET sort_number = '005' WHERE id = 3;
UPDATE units SET sort_number = '006' WHERE id = 4;
UPDATE units SET sort_number = '008' WHERE id = 5;
UPDATE units SET sort_number = '009' WHERE id = 6;
UPDATE units SET sort_number = '018' WHERE id = 7;
UPDATE units SET sort_number = '039' WHERE id = 8;
UPDATE units SET sort_number = '041' WHERE id = 9;
UPDATE units SET sort_number = '043' WHERE id = 10;
UPDATE units SET sort_number = '047' WHERE id = 11;
UPDATE units SET sort_number = '050' WHERE id = 12;
UPDATE units SET sort_number = '051' WHERE id = 13;
UPDATE units SET sort_number = '053' WHERE id = 14;
UPDATE units SET sort_number = '055' WHERE id = 15;
UPDATE units SET sort_number = '058' WHERE id = 16;
UPDATE units SET sort_number = '059' WHERE id = 17;
UPDATE units SET sort_number = '061' WHERE id = 18;
UPDATE units SET sort_number = '071' WHERE id = 19;
UPDATE units SET sort_number = '073' WHERE id = 20;
UPDATE units SET sort_number = '075' WHERE id = 21;
UPDATE units SET sort_number = '109' WHERE id = 22;
UPDATE units SET sort_number = '110' WHERE id = 23;
UPDATE units SET sort_number = '111' WHERE id = 24;
UPDATE units SET sort_number = '112' WHERE id = 25;
UPDATE units SET sort_number = '113' WHERE id = 26;
UPDATE units SET sort_number = '118' WHERE id = 27;
UPDATE units SET sort_number = '122' WHERE id = 28;
UPDATE units SET sort_number = '126' WHERE id = 29;
UPDATE units SET sort_number = '131' WHERE id = 30;
UPDATE units SET sort_number = '132' WHERE id = 31;
UPDATE units SET sort_number = '133' WHERE id = 32;
UPDATE units SET sort_number = '159' WHERE id = 33;
UPDATE units SET sort_number = '160' WHERE id = 34;
UPDATE units SET sort_number = '161' WHERE id = 35;
UPDATE units SET sort_number = '162' WHERE id = 36;
UPDATE units SET sort_number = '163' WHERE id = 37;
UPDATE units SET sort_number = '166' WHERE id = 38;
UPDATE units SET sort_number = '168' WHERE id = 39;
UPDATE units SET sort_number = '170' WHERE id = 40;
UPDATE units SET sort_number = '173' WHERE id = 41;
UPDATE units SET sort_number = '181' WHERE id = 42;
UPDATE units SET sort_number = '185' WHERE id = 43;
UPDATE units SET sort_number = '206' WHERE id = 44;
UPDATE units SET sort_number = '354' WHERE id = 45;
UPDATE units SET sort_number = '355' WHERE id = 46;
UPDATE units SET sort_number = '356' WHERE id = 47;
UPDATE units SET sort_number = '359' WHERE id = 48;
UPDATE units SET sort_number = '360' WHERE id = 49;
UPDATE units SET sort_number = '361' WHERE id = 50;
UPDATE units SET sort_number = '362' WHERE id = 51;
UPDATE units SET sort_number = '364' WHERE id = 52;
UPDATE units SET sort_number = '365' WHERE id = 53;
UPDATE units SET sort_number = '366' WHERE id = 54;
UPDATE units SET sort_number = '368' WHERE id = 55;
UPDATE units SET sort_number = '736' WHERE id = 56;
UPDATE units SET sort_number = '796' WHERE id = 57;
UPDATE units SET sort_number = '812' WHERE id = 58;
UPDATE units SET sort_number = '813' WHERE id = 59;
