server:
  port: 4444

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/trade_accounting
    username: postgres
    password: root

    initialization-mode: always

  mail:
    protocol: smtps
    host: smtp.mail.ru
    port: 465
    username: trade_jm@mail.ru
    password: MaxPowerJM2020

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        format_sql: true
        highlight_sql: true
        jdbc:
          timezone: UTC
  flyway:
    enabled: true
